### Background

### What is Numpy?

Numpy is a multidimensional library. This means that you can use Numpy to store data in one or multiple dimensions.
According to numpy.org:

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

    - a powerful N-dimensional array object

    - sophisticated (broadcasting) functions

    - tools for integrating C/C++ and Fortran code

    - useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to integrate with a wide variety of databases.

### Numpy vs lists ?

Lists are slow whilst Numpy is fast. This is because Numpy uses 'fixed types'.
1. It is faster to read less bytes of memory.
 
 Lists use a inbuilt type in Python that consits of the 
 - object value
 - object type 
 - size 
 - reference count.
 
hence use of lists uses more space. 

2. No type checking when iteratinig through objects.
3. Numpy uses contiguous memory

This means imagine that all the information is not directly next to each other in lists whilst a numpy array uses contiguous memory meaning that the information is stored right next to each other. 

Benefit is that the CPU have a 'SIMD Vector Processing' (single instruction and multiple data) meaning we can compute computations on the vector whith all values next to each other one time. The second benefit is 'Effective Cache Utilization', meaning we can utilize our cache more efficiently.


### Applications of Numpy`

    - Mathematics (MATLAB Replacement)
        Multivariate Calculus Programming (Think of multivariate in R)
        Also consider SciPy documentation for Math
   
    - Plotting (Matplotlib)
    - Backend (Pandas , Digital Photography)
        Numpy is important with Pandas
    - Machine Learning
        Think of Tensor Library, it is very similar to Numpy.
        
    

1. Load in NumPy (pip install numpy first)

In [1]:
import numpy as np
import sys

2. Basics
  - One Dimensional object

In [2]:
a = np.array([1,2,3], dtype='int8')
print(a)  # print vector/matrix

[1 2 3]


In [3]:
print("Dimension", a.ndim)  # Print Number of dimensions

Dimension 1


In [8]:
a.shape # Get the shape?: Its a vector so only the one dimension is given 

(3,)

In [9]:
# Get Type/ Size
print("Type", a.dtype, "Size", a.itemsize, "bytes")

Type int8 Size 1 bytes


  - Two Dimensional object
  
Important to note that you can continue doing this and nest a list whithin a list and so on.

In [5]:
# Create a two dimensional array of floats
b = np.array( [[1.0,2.0,3.0],[4.0,5.0,6.0]] ) 
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
print("Dimension", b.ndim)  # Print Number of dimensions

Dimension 2


In [10]:
b.shape # Rows then columns

(2, 3)

Whant to know how much memory our types are taking up ?

In [12]:

print("Type", b.dtype, "Size", b.itemsize, "bytes")# Get Type/ Size

Type float64 Size 8 bytes
